name: voxgamer
description: "n/a"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  url_launcher: ^6.2.4
  archive: ^3.6.1
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  translator: ^1.0.0
  flutter_local_notifications: ^17.0.0
  wakelock_plus: ^1.2.8
  package_info_plus: ^8.0.0
  shared_preferences: ^2.2.0
  flutter_background_service: ^5.0.0 # Servicio Foreground

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0A0E14"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/
